name: "Upload to GCP Bucket"
description: "Uploads a file to a Google Cloud Storage bucket"
inputs:
  bucket_name:
    description: "The name of the GCP bucket"
    required: true
  file_path:
    description: "The path of the file to upload"
    required: true
  destination_name:
    description: "The destination name of the file in the bucket"
    required: true

runs:
  using: node20
  main: dist/index.js
